# Generated by Django 4.0.4 on 2022-05-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameCategory',
            field=models.ManyToManyField(related_name='gameCategories', to='raterapp.gamecategory'),
        ),
    ]
