# Generated by Django 4.0.4 on 2022-05-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0002_game_gamecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameCategory',
            new_name='category',
        ),
    ]
