# Generated by Django 4.0.4 on 2022-05-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0003_rename_gamecategory_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamerId',
            new_name='gamer',
        ),
    ]
