# Generated by Django 4.0.4 on 2022-05-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0004_rename_gamerid_game_gamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
    ]
