# Generated by Django 4.0.4 on 2022-05-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0006_game_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='gamerId',
            new_name='gamer',
        ),
    ]
