# Generated by Django 4.0.4 on 2022-05-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0007_rename_gameid_review_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='gamerId',
            new_name='gamer',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='gamerId',
            new_name='gamer',
        ),
    ]
